
# Auto-generated using compose2nix v0.2.1-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."homarr" = {
    image = "ghcr.io/ajnart/homarr:latest";
    volumes = [
      "/home/styly/projects/nixserver/network/homarr/configs:/app/data/configs:rw"
      "/home/styly/projects/nixserver/network/homarr/data:/data:rw"
      "/home/styly/projects/nixserver/network/homarr/icons:/app/public/icons:rw"
    ];
    ports = [
      "7575:7575/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homarr"
      "--network=homarr_default"
    ];
  };
  systemd.services."podman-homarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-homarr_default.service"
    ];
    requires = [
      "podman-network-homarr_default.service"
    ];
    partOf = [
      "podman-compose-homarr-root.target"
    ];
    wantedBy = [
      "podman-compose-homarr-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-homarr_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f homarr_default";
    };
    script = ''
      podman network inspect homarr_default || podman network create homarr_default
    '';
    partOf = [ "podman-compose-homarr-root.target" ];
    wantedBy = [ "podman-compose-homarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-homarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
